version: '3.7'

services:

  microservice:
    image: covid-microservice:1.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    #depends_on:
    #  - rabbitmq
      
  #rabbitmq:
   # image: rabbitmq:management
   # ports:
    #  - "5672:5672"
     # - "15672:15672"    