#!/bin/bash

CORE=covid19

echo "Updating covid-19 latest data"

curl -s https://api.covid19india.org/raw_data8.json | jq -r '[.raw_data[] | {entryid : .entryid, patientnumber : .patientnumber, detecteddistrict : .detecteddistrict, detectedstate : .detectedstate, numcases : .numcases, source1 : .source1, statecode : .statecode, dateannounced : .dateannounced, currentstatus : .currentstatus, notes : .notes} ]'  > /covid_data/recent_data.json

/opt/solr/bin/post -c $CORE -commit yes /covid_data/recent_data.json
 
echo "Loaded covid-19 latest data"